# RAFTTrainer configuration file

# RAFTTrainer
#
#         Trainer for RAFT Stereo Model
#
#         Args:
#             lr (float): learning rate
#             max_steps (int): number of steps to train
#             num_epochs (int): number of epochs to train
#             weight_decay (float): weight decay
#             epsilon (float): epsilon for Adam optimizer
#             gradient_accumulation_steps (int): number of steps to accumulate gradients
#             val_interval (Union[float, int]): interval to validate
#             log_interval (int): interval to log
#
lr: 0.0001
num_epochs: 100
max_steps: 100000
weight_decay: 0.0001
epsilon: 1.0e-08
gradient_accumulation_steps: 4

# BaseTrainer
#
#         Base class for all trainers
#
#         Args:
#             workdir (str): path to save the experiment
#             project_name (str): name of the project
#             experiment_name (str): name of the experiment
#             val_interval (Union[float, int]): interval to validate
#             log_interval (int): interval to log
#             num_val_samples (int): number of samples during evaluation.
#                Useful to limit the number of samples during evaluation. Defaults to -1 (all samples)
#             save_best_k_cp (int): number of best checkpoints to save
#
workdir: /weights
project_name: raft_stereo
experiment_name: BaseRaftStereo
val_interval: 10
log_interval: 50
num_val_samples: 10
save_best_k_cp: 3
