dataset_dir: "/data/tartanair"
HW: [384, 384]
batch_size: 1
num_workers: 4
train_envs:
  - abandonedfactory
  - amusement
  - carwelding
  - endofworld
  - gascola
  - hospital
  - japanesealley
  - neighborhood
  - ocean
  - office
  - office2
  - oldtown
  - seasidetown
  - seasonsforest
  - seasonsforest_winter
  - soulcity
  - westerndesert
val_envs:
  - abandonedfactory_night
no_augmentation: true
